name: Docker Update Images

on:
  workflow_dispatch:

  schedule:
    - cron: "0 9 * * 1" # once a week

  pull_request:
    paths:
      - scripts/update_docker_images.py
      - .github/workflows/docker-update-images.yaml

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check and pin updates (if any)
        id: check_update
        run: python3 scripts/update_docker_images.py >> $"GITHUB_OUTPUT"

      - name: Create Pull Request
        if: ${{ steps.check_update.outputs.NEEDS_UPDATE == "True" }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.REPO_TOKEN }}
          commit-message: "Update Docker images"
          title: "Update Docker images"
          body: "Update Docker images"
          base: main
          branch: "docker-update-images"
          delete-branch: true
          team-reviewers: |
            aptos-labs/prod-eng
            aptos-labs/security
